#!/usr/bin/env bash

export LIB_DIR="$HOME/.local/lib/bash"
export DOTFILES_DIR="$HOME/dotfiles"
export BACKUP_DIR="$HOME/backup"

export SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/zsh/scripts/utils"
source "$SCRIPT_DIR/archlinux/scripts/packages"

mkdir -p $LIB_DIR
create_symlink "$DOTFILES_DIR/zsh/scripts/utils" "$LIB_DIR/utils" ""
create_symlink "$DOTFILES_DIR/archlinux/scripts/packages" "$LIB_DIR/packages" ""

packages=(
    "git"
    "neovim"
    "starship"
    "wezterm"
    "yazi"
    "fastfetch"
    "bat"
    "eza"
    "fd"
    "ripgrep"
    "fzf"
    "zoxide"
    "unzip"
    "usbutils"
    "ttf-nerd-fonts-symbols"
    "ttf-cascadia-code-nerd"
    "lazygit"
    "obsidian"
    "godot"
    "proton-pass-bin"
    "proton-mail-bin"
    "mutt"
    "rancher-desktop"
    "devpod-cli-bin"
)
install_packages "${packages[@]}"

# Root files (no subdirectory)
create_symlink "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig" ""
run_script "$SCRIPT_DIR/zsh/setup"
run_script "$SCRIPT_DIR/tmux/setup"

# Config files
create_symlink "$DOTFILES_DIR/wezterm" "$HOME/.config/wezterm" "config"
create_symlink "$DOTFILES_DIR/nvim" "$HOME/.config/nvim" "config"
create_symlink "$DOTFILES_DIR/starship/starship.toml" "$HOME/.config/starship.toml" "config"
create_symlink "$DOTFILES_DIR/yazi" "$HOME/.config/yazi" "config"

run_script "$SCRIPT_DIR/archlinux/hypr/setup"
run_script "$SCRIPT_DIR/devpod/setup"
