command_timeout = 1000
palette = "catppuccin_mocha"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = " "

[git_branch]
symbol = ""
format =  '[$symbol $branch (:$remote_branch)]($style)'

[git_status]
format = '[($all_status$ahead_behind) ]($style)'

[package]
disabled = true

[nodejs]
symbol = ""
format = '[$symbol( $version) ]($style)'

[golang]
symbol = ""
format = '[$symbol( $version) ]($style)'

[python]
symbol = ""
format = '[$symbol( $version) ]($style)'

[docker_context]
symbol = ""
format = '[$symbol( $context) ]($style)'

# #Output the current git config email address
# [custom.git_config_email]
# description = "Output the current git user's configured email address."
# command = "git config user.email"
# format = "\n[$symbol( $output) ]($style)"
# when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
# style = "text"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
