#!/usr/bin/env bash

source "$LIB_DIR/install-utils"
source "$LIB_DIR/package-utils"

print_section "Configuring DevPod"
install_packages "devpod-cli-bin"

devpod-cli ide use none >/dev/null 2>&1
print_success "Set ide use to none"

devpod-cli context set-options -o DOTFILES_URL=git@github.com:piredman/devcontainer-dotfiles.git >/dev/null 2>&1
print_success "Configured dotfiles repository"

provider_count=$(devpod-cli provider list 2>/dev/null | wc -l)
if [ "$provider_count" -eq 0 ]; then
    print_step "Note: Add a provider with 'devpod-cli provider add docker'"
fi
