#!/usr/bin/env bash

source "$LIB_DIR/utils"
source "$LIB_DIR/packages"

theme_packages=(
    "xdg-desktop-portal-gtk"
    "catppuccin-gtk-theme-mocha"
    "catppuccin-qt5ct-git"
    "nwg-look"
    "qt5ct"
    "qt6ct"
)
install_packages "${theme_packages[@]}"

# Default GDK3 to dark mode
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface icon-theme 'breeze'
gsettings set org.gnome.desktop.interface gtk-theme 'catppuccin-mocha-lavender-standard+default'
gsettings set org.gnome.desktop.interface font-name 'CaskaydiaCove Nerd Font 10'

# Default GDK4 to dark mode
# env = GTK_THEME,adw-gtk3-dark

# Qt Theming
create_symlink "$DOTFILES_DIR/archlinux/theme/qt5ct.conf" "$XDG_CONFIG_HOME/qt5ct/qt5ct.conf" "theme"
create_symlink "$DOTFILES_DIR/archlinux/theme/qt6ct.conf" "$XDG_CONFIG_HOME/qt6ct/qt6ct.conf" "theme"
