#!/usr/bin/env bash

source "$LIB_DIR/utils"
source "$LIB_DIR/packages"

theme_packages=(
    "xdg-desktop-portal-gtk"
    "catppuccin-gtk-theme-mocha"
    "catppuccin-qt5ct-git"
    "nwg-look"
    "qt5ct"
    "qt6ct"
)
install_packages "${theme_packages[@]}"

# Gdk Theming
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface icon-theme 'breeze'
gsettings set org.gnome.desktop.interface gtk-theme 'catppuccin-mocha-lavender-standard+default'
gsettings set org.gnome.desktop.interface font-name 'JetBrains Mono 10'

# Qt Theming
create_symlink "$DOTFILES_DIR/archlinux/theme/qt5ct.conf" "$XDG_CONFIG_HOME/qt5ct/qt5ct.conf" "theme"
create_symlink "$DOTFILES_DIR/archlinux/theme/qt6ct.conf" "$XDG_CONFIG_HOME/qt6ct/qt6ct.conf" "theme"
