[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "wezterm start --class wezterm-dropterm"
class = "wezterm-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
