#!/usr/bin/env bash

source "$LIB_DIR/install-utils"
source "$LIB_DIR/symlink-utils"
source "$LIB_DIR/package-utils"

print_section "Installing File Manager Packages"
mapfile -t dolphin_packages < <(load_package_config "$SCRIPT_DIR/install/config/dolphin-packages.conf")
install_packages "${dolphin_packages[@]}"

print_section "Configuring File Manager"
mkdir -p ~/.local/share/kio/servicemenus
create_symlink "$DOTFILES_DIR/archlinux/dolphin/extract-here.desktop" "$HOME/.local/share/kio/servicemenus/extract-here.desktop" ""
chmod +x "$HOME/.local/share/kio/servicemenus/extract-here.desktop"

XDG_MENU_PREFIX=arch- kbuildsycoca6 >/dev/null 2>&1
print_success "Rebuilding desktop database"
