#!/usr/bin/env bash

install_packages() {
    local packages=("$@")

    for package in "${packages[@]}"; do
        if ! paru -Qi "$package" &>/dev/null; then
            echo "Installing $package..."
            paru -S "$package" --noconfirm
        else
            echo "✓ $package"
        fi
    done
}
