#!/usr/bin/env bash

source "$LIB_DIR/install-utils"
source "$LIB_DIR/symlink-utils"

print_section "Configuring Zsh"
create_symlink "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zshrc" ""

if [ ! -d "$HOME/.zsh/zsh-vi-mode" ]; then
    git clone https://github.com/jeffreytse/zsh-vi-mode $HOME/.zsh/zsh-vi-mode >/dev/null 2>&1
fi

if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions >/dev/null 2>&1
fi

if [ ! -d "$HOME/.zsh/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting $HOME/.zsh/zsh-syntax-highlighting >/dev/null 2>&1
fi

if [ ! -d "$HOME/.zsh/zsh-fzf-history-search" ]; then
    git clone https://github.com/joshskidmore/zsh-fzf-history-search $HOME/.zsh/zsh-fzf-history-search >/dev/null 2>&1
fi

print_success "Zsh plugins installed"
